### ISSUE TITLE
Problem running tests with GwtMockitoTestRunner when classpath is assembled at runtime

### ISSUE THREAD

**Issue by bwolff** [google/gwtmockito#5]
Hi,

first I want to say that the GwtMockito lib is really a very nice and promising approach that would benefit us much in testing our GWT client code!

Currently, I'm blocked by a problem to programmatically run the tests with the GwtMockitoTestRunner. When I create a test and use the @RunWith annotation and then use the IntelliJ IDE JUnit test runner to run the class (right-click on the test class) it works. The JUnit runner runs the "java" commands and passes all libs and folders via the -classpath parameter (which is a lot! ;)).

Now I want to run the test from within the Grails framework. The problem is (I believe) that the test classpath is assembled at runtime and before running the tests the current thread's contextClassLoader is modified with all the required libs and folders etc. When I now want to programmatically invoke the GwtMockitoTestRunner the problem is that the custom GwtMockitoClassLoader can't find my test class. The test class is found by the Thread classLoader though.

I'm not really familiar with the JUnit test runner internals, but the only thing I can imagine is that the GwtMockitoClassLoader respects classloader resources passed when the application is started, but not the current context classLoader of the thread?

I checked the sources for the GwtMockitoTestRunner.java and the GwtMockitoClassLoader and it seems that the initialization is done in the constructor and the classloader class is private, so there is no hook to interfere with the classloader resource locations...

I know this description is rather vague, but maybe you already have an idea what the problem may be? If you require additional information I would be happy to provide them.

Maybe we could also produce a small code snippet that show how the GwtTestRunner can be invoked on a test class / test classes in a programmatic way?

Thank you!

Cheers,
Ben

**Comment by dev4light** [comment]
Hi

How did you fixed your setup? I still get an error because the ClassPool is not containing the paths from the overriden getParentClassloader().
In GwtMockitoTestRunner#onLoad(...) the pool.get(name) fails because the paths from the overriden getParentClassloader() are not there.

Thank you

**Comment by ekuefler** [comment]
Ah interesting - yes I think you're right that this is a bug when overriding the parent classloader. We build a class pool based on the system classpath and any provided additional classpaths. But rather than the system classpath, we should actually be using the classpath of the parent classloader (which is the system classpath by default).

I'll create a fix for this, thanks for pointing it out.

**Comment by ekuefler** [comment]
Okay, I think that's all that's needed. Let me know if this works for you.

**Comment by tazle** [comment]
I think the root cause is that you initialize the ClassPool based on "system class path", which is actually based on java.lang.Object. This doesn't seem to be very useful in IDEA's test environment.

In addition to classPool.appendSystemPath() you should perhaps also classPool.appendClassPath(new LoaderClassPath(Thread.getContextClassLoader())). I haven't actually tested this, though.

**Comment by tazle** [comment]
The latest version seems to be something similar already. I'll test with that.

**Comment by tazle** [comment]
When I change getParentClassLoader() to return Thread.currentThread().getContextClassLoader() in master, I can run my tests in IDEA.
